# Generated by Django 5.0.2 on 2025-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(max_length=100)),
                ('descricao_site', models.TextField()),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Classe do ícone Font Awesome (ex: fa-chart-bar)', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
