# Generated by Django 5.0.2 on 2025-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_configuracaosite_contato_depoimento_servico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoSite',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AddField(
            model_name='centro_resultado',
            name='codigo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
