# Generated by Django 5.0.2 on 2025-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_endereco_unidade_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dre',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='dre',
            name='nome',
        ),
        migrations.AddField(
            model_name='dre',
            name='cd_nivel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='cd_nivel2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='nivel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='nivel2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
