# Generated by Django 5.0.2 on 2025-06-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lancamento_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.plano_contas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.empresa')),
            ],
        ),
    ]
