# Generated by Django 5.0.2 on 2025-06-03 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='updated',
        ),
        migrations.AddField(
            model_name='centro_resultado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centro_resultado',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dfc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfcs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dfc',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfcs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dre',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dres_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dre',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dres_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plano_contas',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plano_contas',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dfc',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dfc',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='dfc',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dre',
            name='cd_nivel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dre',
            name='cd_nivel2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dre',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='dre',
            name='nivel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dre',
            name='nivel2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='centro_resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.centro_resultado'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='obs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='plano_contas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plano_contas'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unidade'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plano_contas'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='dfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dfc'),
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='dre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dre'),
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='nivel1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='nivel2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plano_contas',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='centro_resultado',
            table='centro_resultado',
        ),
        migrations.AlterModelTable(
            name='dfc',
            table='dfc',
        ),
        migrations.AlterModelTable(
            name='dre',
            table='dre',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
        migrations.AlterModelTable(
            name='lancamento',
            table='lancamento',
        ),
        migrations.AlterModelTable(
            name='orcamento',
            table='orcamento',
        ),
        migrations.AlterModelTable(
            name='plano_contas',
            table='plano_contas',
        ),
        migrations.AlterModelTable(
            name='unidade',
            table='unidade',
        ),
        migrations.CreateModel(
            name='AcessoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessosEmpresa_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessosEmpresa_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acesso_empresa',
            },
        ),
    ]
