# Generated by Django 5.0.2 on 2025-06-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_orcamento_created_remove_orcamento_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='empresa',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unidade'),
        ),
    ]
