# Generated by Django 5.0.2 on 2025-06-03 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_acessoempresa_empresa_acessoempresa_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoempresa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unidade'),
        ),
        migrations.AlterField(
            model_name='dre',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unidade'),
        ),
    ]
