# Generated by Django 5.0.2 on 2025-06-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_acessoempresa_empresa_alter_centro_resultado_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='centro_resultado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='dre',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empresa'),
        ),
    ]
