# Generated by Django 5.0.2 on 2025-06-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_lancamento_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessoempresa',
            name='empresa',
        ),
    ]
