# Generated by Django 5.0.2 on 2025-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_acessoempresa_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfc',
            name='cd_nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dfc',
            name='cd_nivel2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dfc',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dfc',
            name='nivel2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
