# Generated by Django 5.0.2 on 2025-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_add_ativo_natureza_to_plano_contas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_contas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plano_contas',
            name='natureza',
            field=models.IntegerField(default=1),
        ),
    ]
