# Generated by Django 5.0.2 on 2025-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_empresa_complemento_empresa_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uf',
            old_name='sigla',
            new_name='uf',
        ),
        migrations.AddField(
            model_name='uf',
            name='codigo_uf',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uf',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uf',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uf',
            name='regiao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
