# Generated by Django 5.0.2 on 2025-07-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_sigla_uf_uf_uf_codigo_uf_uf_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'ordering': ('nome',)},
        ),
    ]
