# Generated by Django 5.0.2 on 2025-06-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0006_alter_lancamento_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=40)),
                ('link', models.CharField(max_length=400)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa')),
            ],
            options={
                'db_table': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.link')),
            ],
            options={
                'db_table': 'Acesso',
                'ordering': ['group__name'],
            },
        ),
    ]
