# Generated by Django 5.0.2 on 2025-06-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='links/'),
        ),
    ]
